'use strict';

const POKEMON_DATA = [
  {
    id: 1, name: 'Bulbasaur', emoji: '🌿',
    color: '#78C850', bgColor: '#d4f0b8',
    action: 'feed', actionEmoji: '🍎',
    type: 'Grass',
    description: 'A strange seed was planted on its back at birth. The seed slowly grows larger as this Pokémon grows older.',
  },
  {
    id: 4, name: 'Charmander', emoji: '🔥',
    color: '#F08030', bgColor: '#ffe0c0',
    action: 'play', actionEmoji: '⚽',
    type: 'Fire',
    description: 'Obviously prefers hot places. When it rains, steam is said to spout from the tip of its tail!',
  },
  {
    id: 7, name: 'Squirtle', emoji: '💧',
    color: '#6890F0', bgColor: '#c8dcff',
    action: 'pet', actionEmoji: '🤚',
    type: 'Water',
    description: 'After birth, its back swells and hardens into a shell. It powerfully sprays foam from its mouth.',
  },
  {
    id: 10, name: 'Caterpie', emoji: '🐛',
    color: '#78A820', bgColor: '#d8f0a0',
    action: 'feed', actionEmoji: '🍎',
    type: 'Bug',
    description: 'Its short feet are tipped with suction pads that let it tirelessly climb slopes and walls.',
  },
  {
    id: 16, name: 'Pidgey', emoji: '🐦',
    color: '#A8A878', bgColor: '#e8e8d0',
    action: 'play', actionEmoji: '⚽',
    type: 'Flying',
    description: 'A common sight in forests and woods. It flaps its wings to kick up blinding sand.',
  },
  {
    id: 19, name: 'Rattata', emoji: '🐭',
    color: '#A8A8A8', bgColor: '#e8e8e8',
    action: 'feed', actionEmoji: '🍎',
    type: 'Normal',
    description: 'Will chew on anything with its very sharp fangs. You can hear it gnawing through the night.',
  },
  {
    id: 25, name: 'Pikachu', emoji: '⚡',
    color: '#F8D030', bgColor: '#fff8b0',
    action: 'play', actionEmoji: '⚽',
    type: 'Electric',
    description: 'When several of these Pokémon gather, their electricity can build up and cause lightning storms!',
  },
  {
    id: 35, name: 'Clefairy', emoji: '🌙',
    color: '#F4B8C0', bgColor: '#ffe8f0',
    action: 'pet', actionEmoji: '🤚',
    type: 'Fairy',
    description: 'Its magical and cute appeal has many admirers. It is rare and found only in certain places.',
  },
  {
    id: 39, name: 'Jigglypuff', emoji: '🎵',
    color: '#F8A8C8', bgColor: '#ffe0f0',
    action: 'pet', actionEmoji: '🤚',
    type: 'Normal',
    description: 'When its huge eyes light up, it sings a mysteriously soothing melody that lulls its enemies to sleep.',
  },
  {
    id: 52, name: 'Meowth', emoji: '🐱',
    color: '#F0D898', bgColor: '#fff8d8',
    action: 'feed', actionEmoji: '🍎',
    type: 'Normal',
    description: 'Adores round and shiny things. It wanders the streets at night to look for dropped coins.',
  },
  {
    id: 54, name: 'Psyduck', emoji: '🐤',
    color: '#F8D030', bgColor: '#fffac0',
    action: 'pet', actionEmoji: '🤚',
    type: 'Water',
    description: 'While lulling its enemies with its vacant look, this clever Pokémon uses its psychic powers.',
  },
  {
    id: 94, name: 'Gengar', emoji: '👻',
    color: '#705898', bgColor: '#e8d8ff',
    action: 'play', actionEmoji: '⚽',
    type: 'Ghost',
    description: 'Under a full moon, this Pokémon likes to mimic the shadows of people and laugh at their fright!',
  },
  {
    id: 129, name: 'Magikarp', emoji: '🐟',
    color: '#F85888', bgColor: '#ffd0e0',
    action: 'play', actionEmoji: '⚽',
    type: 'Water',
    description: 'In the distant past, it was somewhat stronger. Today it is the weakest — but it never gives up!',
  },
  {
    id: 133, name: 'Eevee', emoji: '🦊',
    color: '#C88820', bgColor: '#f8e8b0',
    action: 'pet', actionEmoji: '🤚',
    type: 'Normal',
    description: 'Its genetic code is special. It may evolve into many different Pokémon when exposed to special Stones.',
  },
  {
    id: 143, name: 'Snorlax', emoji: '😴',
    color: '#78B8F8', bgColor: '#d0e8ff',
    action: 'feed', actionEmoji: '🍎',
    type: 'Normal',
    description: 'Very lazy. Just eats and sleeps. As its huge body gets bigger, it becomes steadily more sleepy.',
  },
];
