'use strict';

const POKEMON_DATA = [
  {
    id: 1, name: 'Bulbasaur', sprite: 'sprites/001.png', emoji: '🌿',
    color: '#78C850', bgColor: '#d4f0b8',
    action: 'feed', actionEmoji: '🍎',
    type: 'Grass',
    description: 'A strange seed was planted on its back at birth. The seed slowly grows larger as this Pokémon grows older.',
    zones: [0],
  },
  {
    id: 4, name: 'Charmander', sprite: 'sprites/004.png', emoji: '🔥',
    color: '#F08030', bgColor: '#ffe0c0',
    action: 'play', actionEmoji: '⚽',
    type: 'Fire',
    description: 'Obviously prefers hot places. When it rains, steam is said to spout from the tip of its tail!',
    zones: [0],
  },
  {
    id: 7, name: 'Squirtle', sprite: 'sprites/007.png', emoji: '💧',
    color: '#6890F0', bgColor: '#c8dcff',
    action: 'pet', actionEmoji: '🤚',
    type: 'Water',
    description: 'After birth, its back swells and hardens into a shell. It powerfully sprays foam from its mouth.',
    zones: [1],
  },
  {
    id: 10, name: 'Caterpie', sprite: 'sprites/010.png', emoji: '🐛',
    color: '#78A820', bgColor: '#d8f0a0',
    action: 'feed', actionEmoji: '🍎',
    type: 'Bug',
    description: 'Its short feet are tipped with suction pads that let it tirelessly climb slopes and walls.',
    zones: [0],
  },
  {
    id: 16, name: 'Pidgey', sprite: 'sprites/016.png', emoji: '🐦',
    color: '#A8A878', bgColor: '#e8e8d0',
    action: 'play', actionEmoji: '⚽',
    type: 'Flying',
    description: 'A common sight in forests and woods. It flaps its wings to kick up blinding sand.',
    zones: [0],
  },
  {
    id: 19, name: 'Rattata', sprite: 'sprites/019.png', emoji: '🐭',
    color: '#A8A8A8', bgColor: '#e8e8e8',
    action: 'feed', actionEmoji: '🍎',
    type: 'Normal',
    description: 'Will chew on anything with its very sharp fangs. You can hear it gnawing through the night.',
    zones: [0],
  },
  {
    id: 25, name: 'Pikachu', sprite: 'sprites/025.png', emoji: '⚡',
    color: '#F8D030', bgColor: '#fff8b0',
    action: 'play', actionEmoji: '⚽',
    type: 'Electric',
    description: 'When several of these Pokémon gather, their electricity can build up and cause lightning storms!',
    zones: [2],
  },
  {
    id: 35, name: 'Clefairy', sprite: 'sprites/035.png', emoji: '🌙',
    color: '#F4B8C0', bgColor: '#ffe8f0',
    action: 'pet', actionEmoji: '🤚',
    type: 'Fairy',
    description: 'Its magical and cute appeal has many admirers. It is rare and found only in certain places.',
    zones: [3],
  },
  {
    id: 39, name: 'Jigglypuff', sprite: 'sprites/039.png', emoji: '🎵',
    color: '#F8A8C8', bgColor: '#ffe0f0',
    action: 'pet', actionEmoji: '🤚',
    type: 'Normal',
    description: 'When its huge eyes light up, it sings a mysteriously soothing melody that lulls its enemies to sleep.',
    zones: [2],
  },
  {
    id: 52, name: 'Meowth', sprite: 'sprites/052.png', emoji: '🐱',
    color: '#F0D898', bgColor: '#fff8d8',
    action: 'feed', actionEmoji: '🍎',
    type: 'Normal',
    description: 'Adores round and shiny things. It wanders the streets at night to look for dropped coins.',
    zones: [2],
  },
  {
    id: 54, name: 'Psyduck', sprite: 'sprites/054.png', emoji: '🐤',
    color: '#F8D030', bgColor: '#fffac0',
    action: 'pet', actionEmoji: '🤚',
    type: 'Water',
    description: 'While lulling its enemies with its vacant look, this clever Pokémon uses its psychic powers.',
    zones: [1],
  },
  {
    id: 94, name: 'Gengar', sprite: 'sprites/094.png', emoji: '👻',
    color: '#705898', bgColor: '#e8d8ff',
    action: 'play', actionEmoji: '⚽',
    type: 'Ghost',
    description: 'Under a full moon, this Pokémon likes to mimic the shadows of people and laugh at their fright!',
    zones: [3],
  },
  {
    id: 129, name: 'Magikarp', sprite: 'sprites/129.png', emoji: '🐟',
    color: '#F85888', bgColor: '#ffd0e0',
    action: 'play', actionEmoji: '⚽',
    type: 'Water',
    description: 'In the distant past, it was somewhat stronger. Today it is the weakest — but it never gives up!',
    zones: [1],
  },
  {
    id: 133, name: 'Eevee', sprite: 'sprites/133.png', emoji: '🦊',
    color: '#C88820', bgColor: '#f8e8b0',
    action: 'pet', actionEmoji: '🤚',
    type: 'Normal',
    description: 'Its genetic code is special. It may evolve into many different Pokémon when exposed to special Stones.',
    zones: [3],
  },
  {
    id: 143, name: 'Snorlax', sprite: 'sprites/143.png', emoji: '😴',
    color: '#78B8F8', bgColor: '#d0e8ff',
    action: 'feed', actionEmoji: '🍎',
    type: 'Normal',
    description: 'Very lazy. Just eats and sleeps. As its huge body gets bigger, it becomes steadily more sleepy.',
    zones: [2],
  },

  // ── Zone 0 additions ─────────────────────────────────
  {
    id: 12, name: 'Butterfree', sprite: 'sprites/012.png', emoji: '🦋',
    color: '#6890F0', bgColor: '#c8dcff',
    action: 'play', actionEmoji: '⚽',
    type: 'Bug',
    description: 'It flaps its wings at high speed to release highly toxic dust into the air around it.',
    zones: [0],
  },
  {
    id: 13, name: 'Weedle', sprite: 'sprites/013.png', emoji: '🐛',
    color: '#C08030', bgColor: '#f8e0b0',
    action: 'feed', actionEmoji: '🍎',
    type: 'Bug',
    description: 'Often found in forests eating leaves. It has a poisonous spike on its head.',
    zones: [0],
  },
  {
    id: 43, name: 'Oddish', sprite: 'sprites/043.png', emoji: '🌱',
    color: '#3868A8', bgColor: '#b0d0f8',
    action: 'feed', actionEmoji: '🍎',
    type: 'Grass',
    description: 'During the day it buries itself in soil and absorbs nutrients through its feet like a plant.',
    zones: [0],
  },
  {
    id: 46, name: 'Paras', sprite: 'sprites/046.png', emoji: '🍄',
    color: '#F0A848', bgColor: '#ffe4b8',
    action: 'feed', actionEmoji: '🍎',
    type: 'Bug',
    description: 'Mushrooms grow on its back from spores attached at birth. They drain the host\'s energy.',
    zones: [0],
  },
  {
    id: 63, name: 'Abra', sprite: 'sprites/063.png', emoji: '🔮',
    color: '#F8C030', bgColor: '#fff4b0',
    action: 'pet', actionEmoji: '🤚',
    type: 'Psychic',
    description: 'It sleeps 18 hours a day. Even while sleeping it senses danger and can teleport to safety.',
    zones: [0, 3],
  },

  // ── Zone 1 additions (Beach) ──────────────────────────
  {
    id: 60, name: 'Poliwag', sprite: 'sprites/060.png', emoji: '🌀',
    color: '#6890F0', bgColor: '#c8dcff',
    action: 'play', actionEmoji: '⚽',
    type: 'Water',
    description: 'Its spiral belly is transparent skin — you can see its insides! It prefers swampy areas.',
    zones: [1],
  },
  {
    id: 72, name: 'Tentacool', sprite: 'sprites/072.png', emoji: '🔵',
    color: '#3898B8', bgColor: '#a8e8f8',
    action: 'pet', actionEmoji: '🤚',
    type: 'Water',
    description: 'Its body is almost entirely water. It floats in warm seas and stings with its tentacles.',
    zones: [1],
  },
  {
    id: 79, name: 'Slowpoke', sprite: 'sprites/079.png', emoji: '🦦',
    color: '#F8B8D8', bgColor: '#ffe8f8',
    action: 'pet', actionEmoji: '🤚',
    type: 'Water',
    description: 'Incredibly slow and dopey. It takes 5 seconds to feel pain when its tail gets bitten.',
    zones: [1],
  },
  {
    id: 86, name: 'Seel', sprite: 'sprites/086.png', emoji: '🦭',
    color: '#98D8D8', bgColor: '#d8f8f8',
    action: 'play', actionEmoji: '⚽',
    type: 'Water',
    description: 'Loves to sleep in icy water. The colder the weather, the more active and lively it becomes!',
    zones: [1],
  },
  {
    id: 90, name: 'Shellder', sprite: 'sprites/090.png', emoji: '🐚',
    color: '#6878A8', bgColor: '#c8d0f8',
    action: 'pet', actionEmoji: '🤚',
    type: 'Water',
    description: 'Its hard shell deflects any attack. The tongue that hangs from its mouth can snap shut fast.',
    zones: [1],
  },
  {
    id: 98, name: 'Krabby', sprite: 'sprites/098.png', emoji: '🦀',
    color: '#F08030', bgColor: '#ffe0c0',
    action: 'play', actionEmoji: '⚽',
    type: 'Water',
    description: 'Its pincers are both weapons and communication tools — it waves them to send signals.',
    zones: [1],
  },
  {
    id: 116, name: 'Horsea', sprite: 'sprites/116.png', emoji: '🐠',
    color: '#6890F0', bgColor: '#c8dcff',
    action: 'pet', actionEmoji: '🤚',
    type: 'Water',
    description: 'It can swim in any direction including upside down. It squirts ink to escape enemies.',
    zones: [1],
  },
  {
    id: 118, name: 'Goldeen', sprite: 'sprites/118.png', emoji: '🐡',
    color: '#F8A050', bgColor: '#ffe4c0',
    action: 'play', actionEmoji: '⚽',
    type: 'Water',
    description: 'Beautiful but ferocious. One flap of its powerful fin can knock a person clean off their feet.',
    zones: [1],
  },
  {
    id: 120, name: 'Staryu', sprite: 'sprites/120.png', emoji: '⭐',
    color: '#C8A820', bgColor: '#f8e8a0',
    action: 'play', actionEmoji: '⚽',
    type: 'Water',
    description: 'The red gem at its center glows at night. It can regenerate any part of its body that breaks off.',
    zones: [1],
  },
  {
    id: 131, name: 'Lapras', sprite: 'sprites/131.png', emoji: '🦕',
    color: '#6890F0', bgColor: '#c8dcff',
    action: 'pet', actionEmoji: '🤚',
    type: 'Water',
    description: 'A gentle giant that understands human speech and happily carries people across the sea.',
    zones: [1],
  },
  {
    id: 138, name: 'Omanyte', sprite: 'sprites/138.png', emoji: '🐌',
    color: '#7898A8', bgColor: '#c8e0f0',
    action: 'feed', actionEmoji: '🍎',
    type: 'Water',
    description: 'An ancient Pokémon revived from a fossil. It uses its tentacles to capture prey in the sea.',
    zones: [1],
  },

  // ── Zone 2 additions (City) ───────────────────────────
  {
    id: 21, name: 'Spearow', sprite: 'sprites/021.png', emoji: '🦅',
    color: '#A87840', bgColor: '#f0d8b0',
    action: 'feed', actionEmoji: '🍎',
    type: 'Flying',
    description: 'It flaps its small wings rapidly to stay airborne. Its loud, shrill cry can be heard far away.',
    zones: [2],
  },
  {
    id: 41, name: 'Zubat', sprite: 'sprites/041.png', emoji: '🦇',
    color: '#A040A0', bgColor: '#e8b8e8',
    action: 'play', actionEmoji: '⚽',
    type: 'Poison',
    description: 'Hangs upside down in dark places during the day. Has no eyes but navigates perfectly by ultrasound.',
    zones: [2],
  },
  {
    id: 66, name: 'Machop', sprite: 'sprites/066.png', emoji: '💪',
    color: '#905878', bgColor: '#f0d0e8',
    action: 'play', actionEmoji: '⚽',
    type: 'Fighting',
    description: 'Its whole body is composed of pure muscle. Child-sized, but strong enough to throw 100 adults.',
    zones: [2],
  },
  {
    id: 74, name: 'Geodude', sprite: 'sprites/074.png', emoji: '🪨',
    color: '#B8A038', bgColor: '#f0e8b0',
    action: 'pet', actionEmoji: '🤚',
    type: 'Rock',
    description: 'Sleeps deeply in fields and on mountain paths. Hikers often trip over them by mistake.',
    zones: [2],
  },
  {
    id: 81, name: 'Magnemite', sprite: 'sprites/081.png', emoji: '🧲',
    color: '#B8C0C0', bgColor: '#e8f0f0',
    action: 'play', actionEmoji: '⚽',
    type: 'Electric',
    description: 'Floats using magnetism. It is drawn toward people and pets by their body\'s electrical charge.',
    zones: [2],
  },
  {
    id: 92, name: 'Gastly', sprite: 'sprites/092.png', emoji: '💨',
    color: '#705898', bgColor: '#e0d0ff',
    action: 'play', actionEmoji: '⚽',
    type: 'Ghost',
    description: 'Almost invisible, this gaseous Pokémon wraps its opponent in poisonous gas and puts it to sleep.',
    zones: [2],
  },
  {
    id: 96, name: 'Drowzee', sprite: 'sprites/096.png', emoji: '😵',
    color: '#F8C048', bgColor: '#fff0b0',
    action: 'pet', actionEmoji: '🤚',
    type: 'Psychic',
    description: 'If your nose itches while you sleep, a Drowzee is probably nearby, nibbling on your dreams.',
    zones: [2],
  },
  {
    id: 100, name: 'Voltorb', sprite: 'sprites/100.png', emoji: '💣',
    color: '#F03800', bgColor: '#ffc0b0',
    action: 'play', actionEmoji: '⚽',
    type: 'Electric',
    description: 'Looks exactly like a PokéBall. It was first discovered in a power plant. Explodes at the slightest touch.',
    zones: [2],
  },
  {
    id: 132, name: 'Ditto', sprite: 'sprites/132.png', emoji: '💜',
    color: '#7060D0', bgColor: '#d8d0ff',
    action: 'pet', actionEmoji: '🤚',
    type: 'Normal',
    description: 'When it encounters an enemy, its body instantly transforms into a perfect copy of that foe.',
    zones: [2, 3],
  },
  {
    id: 137, name: 'Porygon', sprite: 'sprites/137.png', emoji: '💻',
    color: '#E0A0C8', bgColor: '#f8d8ee',
    action: 'play', actionEmoji: '⚽',
    type: 'Normal',
    description: 'A Pokémon made entirely of programming code. The only artificial Pokémon ever created.',
    zones: [2],
  },

  // ── Zone 3 additions (Highlands) ─────────────────────
  {
    id: 37, name: 'Vulpix', sprite: 'sprites/037.png', emoji: '🐺',
    color: '#C84010', bgColor: '#f8c0a0',
    action: 'pet', actionEmoji: '🤚',
    type: 'Fire',
    description: 'Born with one tail that splits into six as it grows. On cold nights it keeps warm by crossing its tails.',
    zones: [3],
  },
  {
    id: 56, name: 'Mankey', sprite: 'sprites/056.png', emoji: '🐵',
    color: '#F0C0B8', bgColor: '#ffe8e0',
    action: 'play', actionEmoji: '⚽',
    type: 'Fighting',
    description: 'An agile Pokémon that lives in trees. It gets angry at the drop of a hat and attacks on impulse.',
    zones: [3],
  },
  {
    id: 58, name: 'Growlithe', sprite: 'sprites/058.png', emoji: '🐕',
    color: '#F0A030', bgColor: '#ffe4b0',
    action: 'pet', actionEmoji: '🤚',
    type: 'Fire',
    description: 'Very protective of its territory. It will bark and bite to drive off intruders, but is loyal to friends.',
    zones: [3],
  },
  {
    id: 77, name: 'Ponyta', sprite: 'sprites/077.png', emoji: '🐴',
    color: '#F8A038', bgColor: '#ffe4b0',
    action: 'play', actionEmoji: '⚽',
    type: 'Fire',
    description: 'Its legs are as taut as coiled springs. It becomes stronger by jumping over the grass in its habitat.',
    zones: [3],
  },
  {
    id: 104, name: 'Cubone', sprite: 'sprites/104.png', emoji: '💀',
    color: '#B8A038', bgColor: '#f0e4a0',
    action: 'pet', actionEmoji: '🤚',
    type: 'Ground',
    description: 'It always wears the skull of its dead mother. On the night of a full moon, it cries for her.',
    zones: [3],
  },
  {
    id: 115, name: 'Kangaskhan', sprite: 'sprites/115.png', emoji: '🦘',
    color: '#C8A878', bgColor: '#f0e0c0',
    action: 'feed', actionEmoji: '🍎',
    type: 'Normal',
    description: 'The baby in the pouch leaves after three years. The mother fiercely protects it at all costs.',
    zones: [3],
  },
  {
    id: 123, name: 'Scyther', sprite: 'sprites/123.png', emoji: '⚔️',
    color: '#70C850', bgColor: '#d0f8b0',
    action: 'play', actionEmoji: '⚽',
    type: 'Bug',
    description: 'So blindingly fast it becomes invisible. Its razor-sharp scythes can slice through thick logs.',
    zones: [3],
  },
  {
    id: 127, name: 'Pinsir', sprite: 'sprites/127.png', emoji: '🦂',
    color: '#A8A828', bgColor: '#e8e8b0',
    action: 'play', actionEmoji: '⚽',
    type: 'Bug',
    description: 'It grabs prey with its huge pincers and will not let go until the prey splits in two.',
    zones: [3],
  },
  {
    id: 148, name: 'Dragonair', sprite: 'sprites/148.png', emoji: '🐉',
    color: '#6890F0', bgColor: '#c8dcff',
    action: 'pet', actionEmoji: '🤚',
    type: 'Dragon',
    description: 'A mystical Pokémon that can freely control the weather. Spotting one is said to bring good luck.',
    zones: [3],
  },
];
